version: '3'
services:
  app:
    build:
      context: .
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 8080:8080
  #   depends_on:
  #     - "db"

  # db:
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_DATABASE: go_database
  #     MYSQL_ROOT_PASSWORD: root
  #     TZ: 'Asia/Tokyo'
  #   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  #   volumes:
  #     - db-data:/var/lib/mysql
  #     - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
  #   ports:
  #     - 3308:3306

# volumes:
#   db-data:
#     driver: local